### ISSUE TITLE
Problem in "Setup Database" step

### ISSUE THREAD

**Issue by o5k** [kevinastone/django-api-rest-and-angular#17]
When following the steps to setup the project, I get the following errors when I run the `make create_database; make make_fixtures` command. I get the same problems whether running on Django1.7 or 1.8.
```
(venvDjango1.7)[oussama@oussa django-api-rest-and-angular]$ make create_database; make make_fixtures
./manage.py syncdb --noinput
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 27, in handle_noargs
    call_command("migrate", **options)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 63, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/db/migrations/executor.py", line 17, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/db/migrations/loader.py", line 48, in __init__
    self.build_graph()
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/db/migrations/loader.py", line 173, in build_graph
    self.load_disk()
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/db/migrations/loader.py", line 103, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/oussama/PycharmProjects/django-api-rest-and-angular/example/api/migrations/0002_auto_20150427_0318.py", line 9, in <module>
    class Migration(migrations.Migration):
  File "/home/oussama/PycharmProjects/django-api-rest-and-angular/example/api/migrations/0002_auto_20150427_0318.py", line 16, in Migration
    migrations.AlterModelManagers(
AttributeError: 'module' object has no attribute 'AlterModelManagers'
Makefile:5: recipe for target 'create_database' failed
make: *** [create_database] Error 1
./manage.py create_users
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/oussama/PycharmProjects/django-api-rest-and-angular/example/api/management/commands/create_users.py", line 11, in handle
    User.objects.create(username=username, email="{}@example.com".format(username), first_name=user)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/db/models/base.py", line 590, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/db/models/base.py", line 618, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/db/models/base.py", line 699, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/db/models/base.py", line 732, in _do_insert
    using=using, raw=raw)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 920, in execute_sql
    cursor.execute(sql, params)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/oussama/Envs/venvDjango1.7/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: api_user
Makefile:10: recipe for target 'make_fixtures' failed
make: *** [make_fixtures] Error 1
```

**Comment by gabrielrholl** [comment]
I too am running into this issue. Any chance we might get an idea of how to get around this?

**Comment by o5k** [comment]
I resolved the problem and got everything running successfully by first removing the generated database file `$ rm example.sqlite`
Then I tackled the source of the problem, which is clearly the migration phase. I removed the existing migrations in the api app.
`$ rm -rf example/api/migrations`
*The last two commands assume that you are on the root of the cloned project.*
After this the "Setup Database" step will run successfully and the project can be started.

**Comment by kevinastone** [comment]
I updated the migrations, let me know if this problem persists and I'll reopen.

**Comment by Rabia23** [comment]
I am getting the following errors when I run the make create_database; make make_fixtures command.
Please help..

(venv)rabiaiftikhar@rabiaiftikhar:~/Code/django-api-rest-and-angular$ make create_database; make make_fixtures
./manage.py syncdb --noinput
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
make: *** [create_database] Error 1
./manage.py create_users
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
make: *** [make_fixtures] Error 1
(venv)rabiaiftikhar@rabiaiftikhar:~/Code/django-api-rest-and-angular$ rm example.sqlite
rm: cannot remove ‘example.sqlite’: No such file or directory
(venv)rabiaiftikhar@rabiaiftikhar:~/Code/django-api-rest-and-angular$ rm -rf example/api/migrations
(venv)rabiaiftikhar@rabiaiftikhar:~/Code/django-api-rest-and-angular$ make create_database; make make_fixtures
./manage.py syncdb --noinput
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
make: *** [create_database] Error 1
./manage.py create_users
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
make: *** [make_fixtures] Error 1
